### ISSUE TITLE
Add bandit to CI file

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#144]
In GitLab by @pablo-de-andres on Nov 6, 2019, 14:21

Bandit can be added via:
```yml
bandit:
  stage: code_analysis
  script:
    - bandit -r .
```
