### ISSUE TITLE
Add radon to CI file

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#145]
In GitLab by @pablo-de-andres on Nov 6, 2019, 14:27

Radon can be added via:
```yaml
radon:
  stage: code_analysis
  script:
    - radon cc -s -a .
    - radon mi -s .
```
