### ISSUE TITLE
Create 'values' and 'relationships' keys in YML

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#154]
In GitLab by @yoavnash on Nov 11, 2019, 16:50

Now we have:
```
LIVING_BEING:
    definition:
    subclass_of: CUBA.ENTITY
    CUBA.NAME:
      default: "John Smith"
    CUBA.AGE:
      default: 25
    CUBA.IS_CHILD_OF:
      CUBA.LIVING_BEING:
        cardinality: 0-2
```
For readability, perhaps the following is better:
```
LIVING_BEING:
    definition:
    subclass_of: CUBA.ENTITY
    values:
        CUBA.NAME:
            default: "John Smith"
        CUBA.AGE:
            default: 25
    relationships:
        CUBA.IS_CHILD_OF:
            CUBA.LIVING_BEING:
                cardinality: 0-2
```
