### ISSUE TITLE
'description' is not allowed to be empty

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#214]
In GitLab by @yoavnash on Dec 18, 2019, 12:42

This code will return an error because 'description' does not take any value:
```
SEGMENT_POSITION:
    description:
    subclass_of: 
    - OIE.OIE_ENTITY
```
Perhaps this should be allowed.
