### ISSUE TITLE
Meaningful error message for max recursion depth error in pico

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#241]
In GitLab by @urbanmatthias on Jan 30, 2020, 08:31

e.g.

```yml
  VALUE:
    subclass_of:
      - <NAMESPACE>.VALUE
```
