### ISSUE TITLE
Is it possible to define a vector datatype with undefined dimensions?

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#262]
In GitLab by @pablo_lopez_tarifa on Feb 28, 2020, 14:06

Hi, 

I would like to know if there is any way of defining a vector datatype with user-defined dimensions. That is, instead of having to define a "matrix" class for each of the different sizes: 

```
 MATRIX_2X2:
    datatype: VECTOR:FLOAT:2:2
    subclass_of:
    - CUBA.ATTRIBUTE 
 MATRIX_3X2:
    datatype: VECTOR:FLOAT:3:2
    subclass_of:
    - CUBA.ATTRIBUTE
 MATRIX_3X3:
    datatype: VECTOR:FLOAT:3:3
    subclass_of:
    - CUBA.ATTRIBUTE
```

I would like to just define just one: 
```
 MATRIX:
    datatype: VECTOR:FLOAT: D1: D2
    subclass_of:
    - CUBA.ATTRIBUTE 
 ```

where the dimensions D1 and D2 should be parsed as attributes ... somehow. 

The problem came developing the [workflow.ontology](https://gitlab.cc-asp.fraunhofer.de/mat-info/ontology/workflow), where I want to define an entity ELECTRONIC_OCCUPATION entity that is nothing but an array of zeros and ones with variable size: *number_of_atoms x number_of_orbitals*.
