### ISSUE TITLE
new types of relationships

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#28]
In GitLab by @urbanmatthias on May 7, 2019, 16:15

Using only the 'has a' relationship can be restricting and sometimes artificial.
To tackle this, we can add other types of relationships.

The following mechanism has been proposed:
1. There is a 'Relationship' entity in the ontology that all relationships inherit from.
1. The statement `p.add(c)` should be instead `p.add(cuds.classes.HasA().add(c))` if p doesn't already contain a 'HasA' object.
1. The format of the ontology file will be changed as follows:
``` YAML
CUBA.TENSILE_TEST
    definition:
    parent: CUDS.CUDS_ENTITY
    has_a:
        CUDS.SPECIMEN
    performed_at:
        CUDS.LAB    
```
