### ISSUE TITLE
Update documentation of add() --> clarify subelements

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#302]
In GitLab by @pablo_lopez_tarifa on Apr 28, 2020, 16:56

Hi, 

I was wondering if there is any utility to list CUDS objects of a specific superclass. 

For instance, given the following dummy ontology:   

```
UNION:
    description: 'A group of people working together to improve their work lives through collective bargaining.'
STUDENT: 
    description: 'A person who is studying at a university or other place of higher education.'
    disjoint_with: [DUMMY_ONT.WORKER]
WORKER:
    description: 'A person who does a specified type of work or who works in a specified way.'
TEACHER:
    description: 'A person who teaches.'
    subclass_of:
    - DUMMY_ONT.WORKER
PLUMBER:
    description: 'A person who fits and repairs the pipes.'
    subclass_of:
    - DUMMY_ONT.WORKER
 ```

```
> person1=dummy_ont.TEACHER()
> person2=dummy_ont.STUDENT()
> person3=dummy_ont.WORKER()
> union=dummy_ont.UNION()
> union.add( person1, person2, person3)
```
I would like to be able to list any worker (either teacher or plubmer) added to the union object.
