### ISSUE TITLE
Support for default values in YML file

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#37]
In GitLab by @urbanmatthias on Jun 24, 2019, 14:44

Add support for the 'default' attribute which is Currently being ignored. Example:
``` YML
NITROGEN_ATOM:
    definition:
    parent: CUBA.ATOM
    CUBA.NAME:
      default: "N"
      scope: CUBA.SYSTEM
    CUBA.NUMBER:
      default: 7
      scope: CUBA.SYSTEM
```
