### ISSUE TITLE
validate_tree_against_schema gives a false error message

### ISSUE THREAD

**Issue by yoavnash** [simphony/simphony-osp#429]
The function [`validate_tree_against_schema`](https://github.com/simphony/osp-core-migration/blob/7957fcd10e97cfd8abc8ebd4adb50a19fb8c182c/osp/core/utils/schema_validation.py#L18) gives a false error message for the following data model and a cuds structure that has no contact info.

``` yml
---

version: "1.0.0"

oclass: OIE.TEAM

model:
    OIE.TEAM:
        COMMON.HAS_A:
            OIE.CONTACT_INFO:
                cardinality: 0+

    OIE.CONTACT_INFO:
        COMMON.HAS_A:
            COMMON.EMAIL:
                cardinality: 1+

display_value: OIE.TEAM.NAME
```

code:
``` python
team = oie.team()
validate_tree_against_schema(team, 'team.model.yml') # BUG produces error although it should not
```
