### ISSUE TITLE
validate_tree_against_schema gives a false error message for an empty yml file

### ISSUE THREAD

**Issue by yoavnash** [simphony/simphony-osp#430]
The function [`validate_tree_against_schema`](https://github.com/simphony/osp-core-migration/blob/7957fcd10e97cfd8abc8ebd4adb50a19fb8c182c/osp/core/utils/schema_validation.py#L18) gives a false error message for a data model that doesn't specify any constraints (that is, the value of the model keyword is empty).

``` yml
---

version: "1.0.0"

oclass: OIE.TEAM

model:
    OIE.TEAM:
        
display_value: OIE.TEAM.NAME
```

code:
``` python
team = oie.team()
validate_tree_against_schema(team, 'team.model.yml') # BUG produces error although it should not
```
