### ISSUE TITLE
default value of session

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#47]
In GitLab by @urbanmatthias on Aug 7, 2019, 11:06

In the YML file, the default value of a session should be CoreSession. That is:
``` YML
SESSION:
    definition:
    parent: CUBA.VALUE
    default: <CoreSession>
```
However, CoreSession is not a concept in the ontology (nor should it be). Therefore, as a solution, we can use NULL as a default value, that symbolizes internally the CoreSession
