### ISSUE TITLE
Should we define datatypes in the ontology?

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#51]
In GitLab by @urbanmatthias on Aug 19, 2019, 10:38

To store the cuds objects in the database, we usually need to know the datatypes of the cuds objects' values.

## Option 1:
We can define the datatype of the cuds objects in the ontology:
```
NUMBER:
    definition: ...
    parent: CUBA.VALUE
    datatype: INT
```
If no datatype is given, we assume it's a string.

# Option 2:
We assume each datatype is a string.
