### ISSUE TITLE
Extend ontology validity checker

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/simphony-osp#71]
In GitLab by @urbanmatthias on Sep 23, 2019, 15:59

The ontology validity checker should also check if the targets of relationships have the correct format:

```yml
SOME_ENTITY:
  ...
  CUBA.SOME_RELATIONSHIP:
    CUBA.SOME_TARGET:
      invalid_key: some_value  # detect invalid keys here
```
